title: "Dingshan Deng — Research & Software"
description: "Personal academic website"
url: "https://dingshandeng.github.io" # e.g., https://username.github.io
baseurl: "" # e.g., /my-site if using a project page
repository: "" # e.g., username/username.github.io

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "Dingshan Deng"
  avatar: "/assets/images/avatar.png"
  bio: "Protoplanetary Disks • JWST & ALMA"
  location: "Tucson, AZ"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:dingshandeng@arizona.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dingshandeng"
    - label: "ads"
      icon: "ai ai-ads"
      url: "https://ui.adsabs.harvard.edu/search/q=orcid%3A0000-0003-0777-7392&sort=date+desc"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-0777-7392"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=73UPeecAAAAJ"

# Navigation
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

paginate: 5
paginate_path: /news/page:num/

include:
  - _pages

# Build options
markdown: kramdown
kramdown:
  input: GFM

# SEO
logo: /assets/images/avatar.png